/**
 * This class is generated by jOOQ
 */
package io.clickhandler.data.schema.tables;


import io.clickhandler.data.schema.DefaultSchema;
import io.clickhandler.data.schema.Keys;
import io.clickhandler.data.schema.tables.records.EmailRecipientJnlRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailRecipientJnl extends TableImpl<EmailRecipientJnlRecord> {

	private static final long serialVersionUID = 2086121943;

	/**
	 * The reference instance of <code>email_recipient_jnl</code>
	 */
	public static final EmailRecipientJnl EMAIL_RECIPIENT_JNL = new EmailRecipientJnl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EmailRecipientJnlRecord> getRecordType() {
		return EmailRecipientJnlRecord.class;
	}

	/**
	 * The column <code>email_recipient_jnl.id</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>email_recipient_jnl.v</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, Long> V = createField("v", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>email_recipient_jnl.c</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, Timestamp> C = createField("c", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>email_recipient_jnl.email_id</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, String> EMAIL_ID = createField("email_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>email_recipient_jnl.type</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(13), this, "");

	/**
	 * The column <code>email_recipient_jnl.name</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>email_recipient_jnl.address</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>email_recipient_jnl.status</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(19), this, "");

	/**
	 * The column <code>email_recipient_jnl.sent</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, Timestamp> SENT = createField("sent", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>email_recipient_jnl.delivered</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, Timestamp> DELIVERED = createField("delivered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>email_recipient_jnl.bounced</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, Timestamp> BOUNCED = createField("bounced", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>email_recipient_jnl.complaint</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, Timestamp> COMPLAINT = createField("complaint", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>email_recipient_jnl.failed</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, Timestamp> FAILED = createField("failed", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>email_recipient_jnl.opened</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, Timestamp> OPENED = createField("opened", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>email_recipient_jnl.contact_id</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, String> CONTACT_ID = createField("contact_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>email_recipient_jnl.user_id</code>.
	 */
	public final TableField<EmailRecipientJnlRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>email_recipient_jnl</code> table reference
	 */
	public EmailRecipientJnl() {
		this("email_recipient_jnl", null);
	}

	/**
	 * Create an aliased <code>email_recipient_jnl</code> table reference
	 */
	public EmailRecipientJnl(String alias) {
		this(alias, EMAIL_RECIPIENT_JNL);
	}

	private EmailRecipientJnl(String alias, Table<EmailRecipientJnlRecord> aliased) {
		this(alias, aliased, null);
	}

	private EmailRecipientJnl(String alias, Table<EmailRecipientJnlRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EmailRecipientJnlRecord> getPrimaryKey() {
		return Keys.PK_EMAIL_RECIPIENT_JNL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EmailRecipientJnlRecord>> getKeys() {
		return Arrays.<UniqueKey<EmailRecipientJnlRecord>>asList(Keys.PK_EMAIL_RECIPIENT_JNL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnl as(String alias) {
		return new EmailRecipientJnl(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EmailRecipientJnl rename(String name) {
		return new EmailRecipientJnl(name, null);
	}
}
