/**
 * This class is generated by jOOQ
 */
package data.schema.tables.records;


import data.schema.tables.EmailRecipientJnl;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Record2;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailRecipientJnlRecord extends UpdatableRecordImpl<EmailRecipientJnlRecord> implements Record14<String, Long, Timestamp, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, String, String> {

	private static final long serialVersionUID = 692955747;

	/**
	 * Setter for <code>email_recipient_jnl.id</code>.
	 */
	public EmailRecipientJnlRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>email_recipient_jnl.version</code>.
	 */
	public EmailRecipientJnlRecord setVersion(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.version</code>.
	 */
	public Long getVersion() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>email_recipient_jnl.changed</code>.
	 */
	public EmailRecipientJnlRecord setChanged(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.changed</code>.
	 */
	public Timestamp getChanged() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>email_recipient_jnl.type</code>.
	 */
	public EmailRecipientJnlRecord setType(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.type</code>.
	 */
	public String getType() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>email_recipient_jnl.name</code>.
	 */
	public EmailRecipientJnlRecord setName(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.name</code>.
	 */
	public String getName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>email_recipient_jnl.address</code>.
	 */
	public EmailRecipientJnlRecord setAddress(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>email_recipient_jnl.status</code>.
	 */
	public EmailRecipientJnlRecord setStatus(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>email_recipient_jnl.sent</code>.
	 */
	public EmailRecipientJnlRecord setSent(Timestamp value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.sent</code>.
	 */
	public Timestamp getSent() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>email_recipient_jnl.delivered</code>.
	 */
	public EmailRecipientJnlRecord setDelivered(Timestamp value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.delivered</code>.
	 */
	public Timestamp getDelivered() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>email_recipient_jnl.bounced</code>.
	 */
	public EmailRecipientJnlRecord setBounced(Timestamp value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.bounced</code>.
	 */
	public Timestamp getBounced() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>email_recipient_jnl.failed</code>.
	 */
	public EmailRecipientJnlRecord setFailed(Timestamp value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.failed</code>.
	 */
	public Timestamp getFailed() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>email_recipient_jnl.opened</code>.
	 */
	public EmailRecipientJnlRecord setOpened(Timestamp value) {
		setValue(11, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.opened</code>.
	 */
	public Timestamp getOpened() {
		return (Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>email_recipient_jnl.contact_id</code>.
	 */
	public EmailRecipientJnlRecord setContactId(String value) {
		setValue(12, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.contact_id</code>.
	 */
	public String getContactId() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>email_recipient_jnl.user_id</code>.
	 */
	public EmailRecipientJnlRecord setUserId(String value) {
		setValue(13, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient_jnl.user_id</code>.
	 */
	public String getUserId() {
		return (String) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, Long, Timestamp, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, String, String> fieldsRow() {
		return (Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, Long, Timestamp, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, String, String> valuesRow() {
		return (Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.SENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.DELIVERED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.BOUNCED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.FAILED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field12() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.OPENED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.CONTACT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return EmailRecipientJnl.EMAIL_RECIPIENT_JNL.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getChanged();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getSent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getDelivered();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getBounced();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getFailed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value12() {
		return getOpened();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getContactId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value2(Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value3(Timestamp value) {
		setChanged(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value4(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value5(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value6(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value7(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value8(Timestamp value) {
		setSent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value9(Timestamp value) {
		setDelivered(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value10(Timestamp value) {
		setBounced(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value11(Timestamp value) {
		setFailed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value12(Timestamp value) {
		setOpened(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value13(String value) {
		setContactId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord value14(String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientJnlRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9, Timestamp value10, Timestamp value11, Timestamp value12, String value13, String value14) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmailRecipientJnlRecord
	 */
	public EmailRecipientJnlRecord() {
		super(EmailRecipientJnl.EMAIL_RECIPIENT_JNL);
	}

	/**
	 * Create a detached, initialised EmailRecipientJnlRecord
	 */
	public EmailRecipientJnlRecord(String id, Long version, Timestamp changed, String type, String name, String address, String status, Timestamp sent, Timestamp delivered, Timestamp bounced, Timestamp failed, Timestamp opened, String contactId, String userId) {
		super(EmailRecipientJnl.EMAIL_RECIPIENT_JNL);

		setValue(0, id);
		setValue(1, version);
		setValue(2, changed);
		setValue(3, type);
		setValue(4, name);
		setValue(5, address);
		setValue(6, status);
		setValue(7, sent);
		setValue(8, delivered);
		setValue(9, bounced);
		setValue(10, failed);
		setValue(11, opened);
		setValue(12, contactId);
		setValue(13, userId);
	}
}
