/**
 * This class is generated by jOOQ
 */
package data.schema.tables.records;


import data.schema.tables.EmailJnl;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailJnlRecord extends UpdatableRecordImpl<EmailJnlRecord> implements Record9<String, Long, Timestamp, String, String, String, String, String, String> {

	private static final long serialVersionUID = -454432702;

	/**
	 * Setter for <code>email_jnl.id</code>.
	 */
	public EmailJnlRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>email_jnl.version</code>.
	 */
	public EmailJnlRecord setVersion(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.version</code>.
	 */
	public Long getVersion() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>email_jnl.changed</code>.
	 */
	public EmailJnlRecord setChanged(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.changed</code>.
	 */
	public Timestamp getChanged() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>email_jnl.message_id</code>.
	 */
	public EmailJnlRecord setMessageId(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.message_id</code>.
	 */
	public String getMessageId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>email_jnl.store_id</code>.
	 */
	public EmailJnlRecord setStoreId(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.store_id</code>.
	 */
	public String getStoreId() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>email_jnl.html</code>.
	 */
	public EmailJnlRecord setHtml(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.html</code>.
	 */
	public String getHtml() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>email_jnl.html_stripped</code>.
	 */
	public EmailJnlRecord setHtmlStripped(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.html_stripped</code>.
	 */
	public String getHtmlStripped() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>email_jnl.text</code>.
	 */
	public EmailJnlRecord setText(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.text</code>.
	 */
	public String getText() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>email_jnl.text_stripped</code>.
	 */
	public EmailJnlRecord setTextStripped(String value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>email_jnl.text_stripped</code>.
	 */
	public String getTextStripped() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, String, String, String, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, String, String, String, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return EmailJnl.EMAIL_JNL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return EmailJnl.EMAIL_JNL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return EmailJnl.EMAIL_JNL.CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return EmailJnl.EMAIL_JNL.MESSAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return EmailJnl.EMAIL_JNL.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return EmailJnl.EMAIL_JNL.HTML;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return EmailJnl.EMAIL_JNL.HTML_STRIPPED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return EmailJnl.EMAIL_JNL.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return EmailJnl.EMAIL_JNL.TEXT_STRIPPED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getChanged();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMessageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getHtml();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getHtmlStripped();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getTextStripped();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value2(Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value3(Timestamp value) {
		setChanged(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value4(String value) {
		setMessageId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value5(String value) {
		setStoreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value6(String value) {
		setHtml(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value7(String value) {
		setHtmlStripped(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value8(String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord value9(String value) {
		setTextStripped(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailJnlRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmailJnlRecord
	 */
	public EmailJnlRecord() {
		super(EmailJnl.EMAIL_JNL);
	}

	/**
	 * Create a detached, initialised EmailJnlRecord
	 */
	public EmailJnlRecord(String id, Long version, Timestamp changed, String messageId, String storeId, String html, String htmlStripped, String text, String textStripped) {
		super(EmailJnl.EMAIL_JNL);

		setValue(0, id);
		setValue(1, version);
		setValue(2, changed);
		setValue(3, messageId);
		setValue(4, storeId);
		setValue(5, html);
		setValue(6, htmlStripped);
		setValue(7, text);
		setValue(8, textStripped);
	}
}
