/**
 * This class is generated by jOOQ
 */
package data.schema.tables.records;


import data.schema.tables.FileJnl;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Record2;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileJnlRecord extends UpdatableRecordImpl<FileJnlRecord> implements Record16<String, Long, Timestamp, String, String, String, String, String, Integer, Long, String, String, String, String, String, String> {

	private static final long serialVersionUID = 1831918233;

	/**
	 * Setter for <code>file_jnl.id</code>.
	 */
	public FileJnlRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>file_jnl.version</code>.
	 */
	public FileJnlRecord setVersion(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.version</code>.
	 */
	public Long getVersion() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>file_jnl.changed</code>.
	 */
	public FileJnlRecord setChanged(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.changed</code>.
	 */
	public Timestamp getChanged() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>file_jnl.name</code>.
	 */
	public FileJnlRecord setName(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.name</code>.
	 */
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>file_jnl.description</code>.
	 */
	public FileJnlRecord setDescription(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>file_jnl.content_type</code>.
	 */
	public FileJnlRecord setContentType(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.content_type</code>.
	 */
	public String getContentType() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>file_jnl.md5</code>.
	 */
	public FileJnlRecord setMd5(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.md5</code>.
	 */
	public String getMd5() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>file_jnl.etag</code>.
	 */
	public FileJnlRecord setEtag(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.etag</code>.
	 */
	public String getEtag() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>file_jnl.compression</code>.
	 */
	public FileJnlRecord setCompression(Integer value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.compression</code>.
	 */
	public Integer getCompression() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>file_jnl.size</code>.
	 */
	public FileJnlRecord setSize(Long value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.size</code>.
	 */
	public Long getSize() {
		return (Long) getValue(9);
	}

	/**
	 * Setter for <code>file_jnl.store_bucket</code>.
	 */
	public FileJnlRecord setStoreBucket(String value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.store_bucket</code>.
	 */
	public String getStoreBucket() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>file_jnl.store_id</code>.
	 */
	public FileJnlRecord setStoreId(String value) {
		setValue(11, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.store_id</code>.
	 */
	public String getStoreId() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>file_jnl.key_algorithm</code>.
	 */
	public FileJnlRecord setKeyAlgorithm(String value) {
		setValue(12, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.key_algorithm</code>.
	 */
	public String getKeyAlgorithm() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>file_jnl.key_key</code>.
	 */
	public FileJnlRecord setKeyKey(String value) {
		setValue(13, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.key_key</code>.
	 */
	public String getKeyKey() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>file_jnl.key_md5</code>.
	 */
	public FileJnlRecord setKeyMd5(String value) {
		setValue(14, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.key_md5</code>.
	 */
	public String getKeyMd5() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>file_jnl.storage_class</code>.
	 */
	public FileJnlRecord setStorageClass(String value) {
		setValue(15, value);
		return this;
	}

	/**
	 * Getter for <code>file_jnl.storage_class</code>.
	 */
	public String getStorageClass() {
		return (String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<String, Long, Timestamp, String, String, String, String, String, Integer, Long, String, String, String, String, String, String> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<String, Long, Timestamp, String, String, String, String, String, Integer, Long, String, String, String, String, String, String> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return FileJnl.FILE_JNL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return FileJnl.FILE_JNL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return FileJnl.FILE_JNL.CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return FileJnl.FILE_JNL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return FileJnl.FILE_JNL.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return FileJnl.FILE_JNL.CONTENT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return FileJnl.FILE_JNL.MD5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return FileJnl.FILE_JNL.ETAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return FileJnl.FILE_JNL.COMPRESSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field10() {
		return FileJnl.FILE_JNL.SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return FileJnl.FILE_JNL.STORE_BUCKET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return FileJnl.FILE_JNL.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return FileJnl.FILE_JNL.KEY_ALGORITHM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return FileJnl.FILE_JNL.KEY_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return FileJnl.FILE_JNL.KEY_MD5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field16() {
		return FileJnl.FILE_JNL.STORAGE_CLASS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getChanged();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getContentType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getMd5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getEtag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getCompression();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value10() {
		return getSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getStoreBucket();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getKeyAlgorithm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getKeyKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getKeyMd5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value16() {
		return getStorageClass();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value2(Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value3(Timestamp value) {
		setChanged(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value5(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value6(String value) {
		setContentType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value7(String value) {
		setMd5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value8(String value) {
		setEtag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value9(Integer value) {
		setCompression(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value10(Long value) {
		setSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value11(String value) {
		setStoreBucket(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value12(String value) {
		setStoreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value13(String value) {
		setKeyAlgorithm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value14(String value) {
		setKeyKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value15(String value) {
		setKeyMd5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord value16(String value) {
		setStorageClass(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileJnlRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, Integer value9, Long value10, String value11, String value12, String value13, String value14, String value15, String value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FileJnlRecord
	 */
	public FileJnlRecord() {
		super(FileJnl.FILE_JNL);
	}

	/**
	 * Create a detached, initialised FileJnlRecord
	 */
	public FileJnlRecord(String id, Long version, Timestamp changed, String name, String description, String contentType, String md5, String etag, Integer compression, Long size, String storeBucket, String storeId, String keyAlgorithm, String keyKey, String keyMd5, String storageClass) {
		super(FileJnl.FILE_JNL);

		setValue(0, id);
		setValue(1, version);
		setValue(2, changed);
		setValue(3, name);
		setValue(4, description);
		setValue(5, contentType);
		setValue(6, md5);
		setValue(7, etag);
		setValue(8, compression);
		setValue(9, size);
		setValue(10, storeBucket);
		setValue(11, storeId);
		setValue(12, keyAlgorithm);
		setValue(13, keyKey);
		setValue(14, keyMd5);
		setValue(15, storageClass);
	}
}
