/**
 * This class is generated by jOOQ
 */
package data.schema.tables.records;


import data.schema.tables.File;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> implements Record16<String, Long, Timestamp, String, String, String, String, String, Integer, Long, String, String, String, String, String, String> {

	private static final long serialVersionUID = 1578782610;

	/**
	 * Setter for <code>file.id</code>.
	 */
	public FileRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>file.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>file.version</code>.
	 */
	public FileRecord setVersion(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>file.version</code>.
	 */
	public Long getVersion() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>file.changed</code>.
	 */
	public FileRecord setChanged(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>file.changed</code>.
	 */
	public Timestamp getChanged() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>file.name</code>.
	 */
	public FileRecord setName(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>file.name</code>.
	 */
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>file.description</code>.
	 */
	public FileRecord setDescription(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>file.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>file.content_type</code>.
	 */
	public FileRecord setContentType(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>file.content_type</code>.
	 */
	public String getContentType() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>file.md5</code>.
	 */
	public FileRecord setMd5(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>file.md5</code>.
	 */
	public String getMd5() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>file.etag</code>.
	 */
	public FileRecord setEtag(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>file.etag</code>.
	 */
	public String getEtag() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>file.compression</code>.
	 */
	public FileRecord setCompression(Integer value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>file.compression</code>.
	 */
	public Integer getCompression() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>file.size</code>.
	 */
	public FileRecord setSize(Long value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>file.size</code>.
	 */
	public Long getSize() {
		return (Long) getValue(9);
	}

	/**
	 * Setter for <code>file.store_bucket</code>.
	 */
	public FileRecord setStoreBucket(String value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>file.store_bucket</code>.
	 */
	public String getStoreBucket() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>file.store_id</code>.
	 */
	public FileRecord setStoreId(String value) {
		setValue(11, value);
		return this;
	}

	/**
	 * Getter for <code>file.store_id</code>.
	 */
	public String getStoreId() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>file.key_algorithm</code>.
	 */
	public FileRecord setKeyAlgorithm(String value) {
		setValue(12, value);
		return this;
	}

	/**
	 * Getter for <code>file.key_algorithm</code>.
	 */
	public String getKeyAlgorithm() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>file.key_key</code>.
	 */
	public FileRecord setKeyKey(String value) {
		setValue(13, value);
		return this;
	}

	/**
	 * Getter for <code>file.key_key</code>.
	 */
	public String getKeyKey() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>file.key_md5</code>.
	 */
	public FileRecord setKeyMd5(String value) {
		setValue(14, value);
		return this;
	}

	/**
	 * Getter for <code>file.key_md5</code>.
	 */
	public String getKeyMd5() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>file.storage_class</code>.
	 */
	public FileRecord setStorageClass(String value) {
		setValue(15, value);
		return this;
	}

	/**
	 * Getter for <code>file.storage_class</code>.
	 */
	public String getStorageClass() {
		return (String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<String, Long, Timestamp, String, String, String, String, String, Integer, Long, String, String, String, String, String, String> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<String, Long, Timestamp, String, String, String, String, String, Integer, Long, String, String, String, String, String, String> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return File.FILE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return File.FILE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return File.FILE.CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return File.FILE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return File.FILE.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return File.FILE.CONTENT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return File.FILE.MD5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return File.FILE.ETAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return File.FILE.COMPRESSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field10() {
		return File.FILE.SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return File.FILE.STORE_BUCKET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return File.FILE.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return File.FILE.KEY_ALGORITHM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return File.FILE.KEY_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return File.FILE.KEY_MD5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field16() {
		return File.FILE.STORAGE_CLASS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getChanged();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getContentType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getMd5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getEtag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getCompression();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value10() {
		return getSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getStoreBucket();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getKeyAlgorithm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getKeyKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getKeyMd5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value16() {
		return getStorageClass();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value2(Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value3(Timestamp value) {
		setChanged(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value5(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value6(String value) {
		setContentType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value7(String value) {
		setMd5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value8(String value) {
		setEtag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value9(Integer value) {
		setCompression(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value10(Long value) {
		setSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value11(String value) {
		setStoreBucket(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value12(String value) {
		setStoreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value13(String value) {
		setKeyAlgorithm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value14(String value) {
		setKeyKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value15(String value) {
		setKeyMd5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord value16(String value) {
		setStorageClass(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FileRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, Integer value9, Long value10, String value11, String value12, String value13, String value14, String value15, String value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FileRecord
	 */
	public FileRecord() {
		super(File.FILE);
	}

	/**
	 * Create a detached, initialised FileRecord
	 */
	public FileRecord(String id, Long version, Timestamp changed, String name, String description, String contentType, String md5, String etag, Integer compression, Long size, String storeBucket, String storeId, String keyAlgorithm, String keyKey, String keyMd5, String storageClass) {
		super(File.FILE);

		setValue(0, id);
		setValue(1, version);
		setValue(2, changed);
		setValue(3, name);
		setValue(4, description);
		setValue(5, contentType);
		setValue(6, md5);
		setValue(7, etag);
		setValue(8, compression);
		setValue(9, size);
		setValue(10, storeBucket);
		setValue(11, storeId);
		setValue(12, keyAlgorithm);
		setValue(13, keyKey);
		setValue(14, keyMd5);
		setValue(15, storageClass);
	}
}
