/**
 * This class is generated by jOOQ
 */
package data.schema.tables.records;


import data.schema.tables.SNSNotification;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SNSNotificationRecord extends UpdatableRecordImpl<SNSNotificationRecord> implements Record9<String, Long, Timestamp, String, String, String, String, String, Timestamp> {

	private static final long serialVersionUID = -1233912243;

	/**
	 * Setter for <code>s_n_s_notification.id</code>.
	 */
	public SNSNotificationRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>s_n_s_notification.version</code>.
	 */
	public SNSNotificationRecord setVersion(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.version</code>.
	 */
	public Long getVersion() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>s_n_s_notification.changed</code>.
	 */
	public SNSNotificationRecord setChanged(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.changed</code>.
	 */
	public Timestamp getChanged() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>s_n_s_notification.type</code>.
	 */
	public SNSNotificationRecord setType(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.type</code>.
	 */
	public String getType() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>s_n_s_notification.message_id</code>.
	 */
	public SNSNotificationRecord setMessageId(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.message_id</code>.
	 */
	public String getMessageId() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>s_n_s_notification.topic_arn</code>.
	 */
	public SNSNotificationRecord setTopicArn(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.topic_arn</code>.
	 */
	public String getTopicArn() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>s_n_s_notification.subject</code>.
	 */
	public SNSNotificationRecord setSubject(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.subject</code>.
	 */
	public String getSubject() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>s_n_s_notification.message</code>.
	 */
	public SNSNotificationRecord setMessage(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.message</code>.
	 */
	public String getMessage() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>s_n_s_notification.date</code>.
	 */
	public SNSNotificationRecord setDate(Timestamp value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification.date</code>.
	 */
	public Timestamp getDate() {
		return (Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, String, String, String, Timestamp> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, String, String, String, Timestamp> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return SNSNotification.S_N_S_NOTIFICATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return SNSNotification.S_N_S_NOTIFICATION.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return SNSNotification.S_N_S_NOTIFICATION.CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return SNSNotification.S_N_S_NOTIFICATION.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return SNSNotification.S_N_S_NOTIFICATION.MESSAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return SNSNotification.S_N_S_NOTIFICATION.TOPIC_ARN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return SNSNotification.S_N_S_NOTIFICATION.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return SNSNotification.S_N_S_NOTIFICATION.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return SNSNotification.S_N_S_NOTIFICATION.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getChanged();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getMessageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getTopicArn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value2(Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value3(Timestamp value) {
		setChanged(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value4(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value5(String value) {
		setMessageId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value6(String value) {
		setTopicArn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value7(String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value8(String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord value9(Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, Timestamp value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SNSNotificationRecord
	 */
	public SNSNotificationRecord() {
		super(SNSNotification.S_N_S_NOTIFICATION);
	}

	/**
	 * Create a detached, initialised SNSNotificationRecord
	 */
	public SNSNotificationRecord(String id, Long version, Timestamp changed, String type, String messageId, String topicArn, String subject, String message, Timestamp date) {
		super(SNSNotification.S_N_S_NOTIFICATION);

		setValue(0, id);
		setValue(1, version);
		setValue(2, changed);
		setValue(3, type);
		setValue(4, messageId);
		setValue(5, topicArn);
		setValue(6, subject);
		setValue(7, message);
		setValue(8, date);
	}
}
