/**
 * This class is generated by jOOQ
 */
package data.schema.tables.records;


import data.schema.tables.SNSNotificationJnl;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SNSNotificationJnlRecord extends UpdatableRecordImpl<SNSNotificationJnlRecord> implements Record9<String, Long, Timestamp, String, String, String, String, String, Timestamp> {

	private static final long serialVersionUID = 1676300135;

	/**
	 * Setter for <code>s_n_s_notification_jnl.id</code>.
	 */
	public SNSNotificationJnlRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>s_n_s_notification_jnl.version</code>.
	 */
	public SNSNotificationJnlRecord setVersion(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.version</code>.
	 */
	public Long getVersion() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>s_n_s_notification_jnl.changed</code>.
	 */
	public SNSNotificationJnlRecord setChanged(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.changed</code>.
	 */
	public Timestamp getChanged() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>s_n_s_notification_jnl.type</code>.
	 */
	public SNSNotificationJnlRecord setType(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.type</code>.
	 */
	public String getType() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>s_n_s_notification_jnl.message_id</code>.
	 */
	public SNSNotificationJnlRecord setMessageId(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.message_id</code>.
	 */
	public String getMessageId() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>s_n_s_notification_jnl.topic_arn</code>.
	 */
	public SNSNotificationJnlRecord setTopicArn(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.topic_arn</code>.
	 */
	public String getTopicArn() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>s_n_s_notification_jnl.subject</code>.
	 */
	public SNSNotificationJnlRecord setSubject(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.subject</code>.
	 */
	public String getSubject() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>s_n_s_notification_jnl.message</code>.
	 */
	public SNSNotificationJnlRecord setMessage(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.message</code>.
	 */
	public String getMessage() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>s_n_s_notification_jnl.date</code>.
	 */
	public SNSNotificationJnlRecord setDate(Timestamp value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>s_n_s_notification_jnl.date</code>.
	 */
	public Timestamp getDate() {
		return (Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, String, String, String, Timestamp> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, String, String, String, Timestamp> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.MESSAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.TOPIC_ARN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return SNSNotificationJnl.S_N_S_NOTIFICATION_JNL.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getChanged();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getMessageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getTopicArn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value2(Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value3(Timestamp value) {
		setChanged(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value4(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value5(String value) {
		setMessageId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value6(String value) {
		setTopicArn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value7(String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value8(String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord value9(Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnlRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, Timestamp value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SNSNotificationJnlRecord
	 */
	public SNSNotificationJnlRecord() {
		super(SNSNotificationJnl.S_N_S_NOTIFICATION_JNL);
	}

	/**
	 * Create a detached, initialised SNSNotificationJnlRecord
	 */
	public SNSNotificationJnlRecord(String id, Long version, Timestamp changed, String type, String messageId, String topicArn, String subject, String message, Timestamp date) {
		super(SNSNotificationJnl.S_N_S_NOTIFICATION_JNL);

		setValue(0, id);
		setValue(1, version);
		setValue(2, changed);
		setValue(3, type);
		setValue(4, messageId);
		setValue(5, topicArn);
		setValue(6, subject);
		setValue(7, message);
		setValue(8, date);
	}
}
