/**
 * This class is generated by jOOQ
 */
package data.schema.tables;


import data.schema.DefaultSchema;
import data.schema.Keys;
import data.schema.tables.records.EmailRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Email extends TableImpl<EmailRecord> {

	private static final long serialVersionUID = -582851955;

	/**
	 * The reference instance of <code>email</code>
	 */
	public static final Email EMAIL = new Email();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EmailRecord> getRecordType() {
		return EmailRecord.class;
	}

	/**
	 * The column <code>email.id</code>.
	 */
	public final TableField<EmailRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>email.version</code>.
	 */
	public final TableField<EmailRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>email.changed</code>.
	 */
	public final TableField<EmailRecord, Timestamp> CHANGED = createField("changed", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>email.message_id</code>.
	 */
	public final TableField<EmailRecord, String> MESSAGE_ID = createField("message_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>email.store_id</code>.
	 */
	public final TableField<EmailRecord, String> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>email.html</code>.
	 */
	public final TableField<EmailRecord, String> HTML = createField("html", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>email.html_stripped</code>.
	 */
	public final TableField<EmailRecord, String> HTML_STRIPPED = createField("html_stripped", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>email.text</code>.
	 */
	public final TableField<EmailRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>email.text_stripped</code>.
	 */
	public final TableField<EmailRecord, String> TEXT_STRIPPED = createField("text_stripped", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * Create a <code>email</code> table reference
	 */
	public Email() {
		this("email", null);
	}

	/**
	 * Create an aliased <code>email</code> table reference
	 */
	public Email(String alias) {
		this(alias, EMAIL);
	}

	private Email(String alias, Table<EmailRecord> aliased) {
		this(alias, aliased, null);
	}

	private Email(String alias, Table<EmailRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EmailRecord> getPrimaryKey() {
		return Keys.PK_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EmailRecord>> getKeys() {
		return Arrays.<UniqueKey<EmailRecord>>asList(Keys.PK_EMAIL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<EmailRecord, Long> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<EmailRecord, Timestamp> getRecordTimestamp() {
		return CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Email as(String alias) {
		return new Email(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Email rename(String name) {
		return new Email(name, null);
	}
}
