/**
 * This class is generated by jOOQ
 */
package io.clickhandler.email.schema.tables.records;


import io.clickhandler.email.schema.tables.EvolutionChange;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ v:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EvolutionChangeRecord extends UpdatableRecordImpl<EvolutionChangeRecord> implements Record9<String, Long, Timestamp, String, String, Timestamp, Boolean, Long, String> {

	private static final long serialVersionUID = -973733542;

	/**
	 * Setter for <code>evolution_change.id</code>.
	 */
	public EvolutionChangeRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>evolution_change.v</code>.
	 */
	public EvolutionChangeRecord setV(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.v</code>.
	 */
	public Long getV() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>evolution_change.c</code>.
	 */
	public EvolutionChangeRecord setC(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.c</code>.
	 */
	public Timestamp getC() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>evolution_change.type</code>.
	 */
	public EvolutionChangeRecord setType(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.type</code>.
	 */
	public String getType() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>evolution_change.sql</code>.
	 */
	public EvolutionChangeRecord setSql(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.sql</code>.
	 */
	public String getSql() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>evolution_change.end</code>.
	 */
	public EvolutionChangeRecord setEnd(Timestamp value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.end</code>.
	 */
	public Timestamp getEnd() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>evolution_change.success</code>.
	 */
	public EvolutionChangeRecord setSuccess(Boolean value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.success</code>.
	 */
	public Boolean getSuccess() {
		return (Boolean) getValue(6);
	}

	/**
	 * Setter for <code>evolution_change.affected</code>.
	 */
	public EvolutionChangeRecord setAffected(Long value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.affected</code>.
	 */
	public Long getAffected() {
		return (Long) getValue(7);
	}

	/**
	 * Setter for <code>evolution_change.message</code>.
	 */
	public EvolutionChangeRecord setMessage(String value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>evolution_change.message</code>.
	 */
	public String getMessage() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, Timestamp, Boolean, Long, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, Timestamp, Boolean, Long, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return EvolutionChange.EVOLUTION_CHANGE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return EvolutionChange.EVOLUTION_CHANGE.V;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return EvolutionChange.EVOLUTION_CHANGE.C;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return EvolutionChange.EVOLUTION_CHANGE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return EvolutionChange.EVOLUTION_CHANGE.SQL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return EvolutionChange.EVOLUTION_CHANGE.END;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return EvolutionChange.EVOLUTION_CHANGE.SUCCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field8() {
		return EvolutionChange.EVOLUTION_CHANGE.AFFECTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return EvolutionChange.EVOLUTION_CHANGE.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getV();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getC();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getSql();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getEnd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getSuccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value8() {
		return getAffected();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value2(Long value) {
		setV(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value3(Timestamp value) {
		setC(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value4(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value5(String value) {
		setSql(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value6(Timestamp value) {
		setEnd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value7(Boolean value) {
		setSuccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value8(Long value) {
		setAffected(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord value9(String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvolutionChangeRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, Timestamp value6, Boolean value7, Long value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EvolutionChangeRecord
	 */
	public EvolutionChangeRecord() {
		super(EvolutionChange.EVOLUTION_CHANGE);
	}

	/**
	 * Create a detached, initialised EvolutionChangeRecord
	 */
	public EvolutionChangeRecord(String id, Long v, Timestamp c, String type, String sql, Timestamp end, Boolean success, Long affected, String message) {
		super(EvolutionChange.EVOLUTION_CHANGE);

		setValue(0, id);
		setValue(1, v);
		setValue(2, c);
		setValue(3, type);
		setValue(4, sql);
		setValue(5, end);
		setValue(6, success);
		setValue(7, affected);
		setValue(8, message);
	}
}
