/**
 * This class is generated by jOOQ
 */
package io.clickhandler.data.schema.tables;


import io.clickhandler.data.schema.DefaultSchema;
import io.clickhandler.data.schema.Keys;
import io.clickhandler.data.schema.tables.records.FileRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class File extends TableImpl<FileRecord> {

	private static final long serialVersionUID = 1352910585;

	/**
	 * The reference instance of <code>file</code>
	 */
	public static final File FILE = new File();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FileRecord> getRecordType() {
		return FileRecord.class;
	}

	/**
	 * The column <code>file.id</code>.
	 */
	public final TableField<FileRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>file.v</code>.
	 */
	public final TableField<FileRecord, Long> V = createField("v", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>file.c</code>.
	 */
	public final TableField<FileRecord, Timestamp> C = createField("c", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>file.name</code>.
	 */
	public final TableField<FileRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>file.description</code>.
	 */
	public final TableField<FileRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>file.content_type</code>.
	 */
	public final TableField<FileRecord, String> CONTENT_TYPE = createField("content_type", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>file.md5</code>.
	 */
	public final TableField<FileRecord, String> MD5 = createField("md5", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>file.etag</code>.
	 */
	public final TableField<FileRecord, String> ETAG = createField("etag", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>file.compression</code>.
	 */
	public final TableField<FileRecord, Integer> COMPRESSION = createField("compression", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>file.size</code>.
	 */
	public final TableField<FileRecord, Long> SIZE = createField("size", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>file.store_bucket</code>.
	 */
	public final TableField<FileRecord, String> STORE_BUCKET = createField("store_bucket", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>file.store_id</code>.
	 */
	public final TableField<FileRecord, String> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>file.key_algorithm</code>.
	 */
	public final TableField<FileRecord, String> KEY_ALGORITHM = createField("key_algorithm", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>file.key_key</code>.
	 */
	public final TableField<FileRecord, String> KEY_KEY = createField("key_key", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>file.key_md5</code>.
	 */
	public final TableField<FileRecord, String> KEY_MD5 = createField("key_md5", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>file.storage_class</code>.
	 */
	public final TableField<FileRecord, String> STORAGE_CLASS = createField("storage_class", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>file.status</code>.
	 */
	public final TableField<FileRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(19), this, "");

	/**
	 * Create a <code>file</code> table reference
	 */
	public File() {
		this("file", null);
	}

	/**
	 * Create an aliased <code>file</code> table reference
	 */
	public File(String alias) {
		this(alias, FILE);
	}

	private File(String alias, Table<FileRecord> aliased) {
		this(alias, aliased, null);
	}

	private File(String alias, Table<FileRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FileRecord> getPrimaryKey() {
		return Keys.PK_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FileRecord>> getKeys() {
		return Arrays.<UniqueKey<FileRecord>>asList(Keys.PK_FILE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public File as(String alias) {
		return new File(alias, this);
	}

	/**
	 * Rename this table
	 */
	public File rename(String name) {
		return new File(name, null);
	}
}
