/**
 * This class is generated by jOOQ
 */
package io.clickhandler.data.schema.tables.records;


import io.clickhandler.data.schema.tables.EmailRecipient;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ v:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailRecipientRecord extends UpdatableRecordImpl<EmailRecipientRecord> implements Record16<String, Long, Timestamp, String, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, String, String> {

	private static final long serialVersionUID = -450232874;

	/**
	 * Setter for <code>email_recipient.id</code>.
	 */
	public EmailRecipientRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>email_recipient.v</code>.
	 */
	public EmailRecipientRecord setV(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.v</code>.
	 */
	public Long getV() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>email_recipient.c</code>.
	 */
	public EmailRecipientRecord setC(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.c</code>.
	 */
	public Timestamp getC() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>email_recipient.email_id</code>.
	 */
	public EmailRecipientRecord setEmailId(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.email_id</code>.
	 */
	public String getEmailId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>email_recipient.type</code>.
	 */
	public EmailRecipientRecord setType(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.type</code>.
	 */
	public String getType() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>email_recipient.name</code>.
	 */
	public EmailRecipientRecord setName(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.name</code>.
	 */
	public String getName() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>email_recipient.address</code>.
	 */
	public EmailRecipientRecord setAddress(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>email_recipient.status</code>.
	 */
	public EmailRecipientRecord setStatus(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>email_recipient.sent</code>.
	 */
	public EmailRecipientRecord setSent(Timestamp value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.sent</code>.
	 */
	public Timestamp getSent() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>email_recipient.delivered</code>.
	 */
	public EmailRecipientRecord setDelivered(Timestamp value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.delivered</code>.
	 */
	public Timestamp getDelivered() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>email_recipient.bounced</code>.
	 */
	public EmailRecipientRecord setBounced(Timestamp value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.bounced</code>.
	 */
	public Timestamp getBounced() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>email_recipient.complaint</code>.
	 */
	public EmailRecipientRecord setComplaint(Timestamp value) {
		setValue(11, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.complaint</code>.
	 */
	public Timestamp getComplaint() {
		return (Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>email_recipient.failed</code>.
	 */
	public EmailRecipientRecord setFailed(Timestamp value) {
		setValue(12, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.failed</code>.
	 */
	public Timestamp getFailed() {
		return (Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>email_recipient.opened</code>.
	 */
	public EmailRecipientRecord setOpened(Timestamp value) {
		setValue(13, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.opened</code>.
	 */
	public Timestamp getOpened() {
		return (Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>email_recipient.contact_id</code>.
	 */
	public EmailRecipientRecord setContactId(String value) {
		setValue(14, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.contact_id</code>.
	 */
	public String getContactId() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>email_recipient.user_id</code>.
	 */
	public EmailRecipientRecord setUserId(String value) {
		setValue(15, value);
		return this;
	}

	/**
	 * Getter for <code>email_recipient.user_id</code>.
	 */
	public String getUserId() {
		return (String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<String, Long, Timestamp, String, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, String, String> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<String, Long, Timestamp, String, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, Timestamp, String, String> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return EmailRecipient.EMAIL_RECIPIENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return EmailRecipient.EMAIL_RECIPIENT.V;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return EmailRecipient.EMAIL_RECIPIENT.C;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return EmailRecipient.EMAIL_RECIPIENT.EMAIL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return EmailRecipient.EMAIL_RECIPIENT.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return EmailRecipient.EMAIL_RECIPIENT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return EmailRecipient.EMAIL_RECIPIENT.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return EmailRecipient.EMAIL_RECIPIENT.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return EmailRecipient.EMAIL_RECIPIENT.SENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return EmailRecipient.EMAIL_RECIPIENT.DELIVERED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return EmailRecipient.EMAIL_RECIPIENT.BOUNCED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field12() {
		return EmailRecipient.EMAIL_RECIPIENT.COMPLAINT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field13() {
		return EmailRecipient.EMAIL_RECIPIENT.FAILED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field14() {
		return EmailRecipient.EMAIL_RECIPIENT.OPENED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return EmailRecipient.EMAIL_RECIPIENT.CONTACT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field16() {
		return EmailRecipient.EMAIL_RECIPIENT.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getV();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getC();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getEmailId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getSent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getDelivered();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getBounced();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value12() {
		return getComplaint();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value13() {
		return getFailed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value14() {
		return getOpened();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getContactId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value16() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value2(Long value) {
		setV(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value3(Timestamp value) {
		setC(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value4(String value) {
		setEmailId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value5(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value6(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value7(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value8(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value9(Timestamp value) {
		setSent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value10(Timestamp value) {
		setDelivered(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value11(Timestamp value) {
		setBounced(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value12(Timestamp value) {
		setComplaint(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value13(Timestamp value) {
		setFailed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value14(Timestamp value) {
		setOpened(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value15(String value) {
		setContactId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord value16(String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecipientRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, Timestamp value9, Timestamp value10, Timestamp value11, Timestamp value12, Timestamp value13, Timestamp value14, String value15, String value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmailRecipientRecord
	 */
	public EmailRecipientRecord() {
		super(EmailRecipient.EMAIL_RECIPIENT);
	}

	/**
	 * Create a detached, initialised EmailRecipientRecord
	 */
	public EmailRecipientRecord(String id, Long v, Timestamp c, String emailId, String type, String name, String address, String status, Timestamp sent, Timestamp delivered, Timestamp bounced, Timestamp complaint, Timestamp failed, Timestamp opened, String contactId, String userId) {
		super(EmailRecipient.EMAIL_RECIPIENT);

		setValue(0, id);
		setValue(1, v);
		setValue(2, c);
		setValue(3, emailId);
		setValue(4, type);
		setValue(5, name);
		setValue(6, address);
		setValue(7, status);
		setValue(8, sent);
		setValue(9, delivered);
		setValue(10, bounced);
		setValue(11, complaint);
		setValue(12, failed);
		setValue(13, opened);
		setValue(14, contactId);
		setValue(15, userId);
	}
}
