/**
 * This class is generated by jOOQ
 */
package io.clickhandler.cloud.model;


import io.clickhandler.cloud.model.tables.Email;
import io.clickhandler.cloud.model.tables.EmailAttachment;
import io.clickhandler.cloud.model.tables.EmailAttachmentJnl;
import io.clickhandler.cloud.model.tables.EmailJnl;
import io.clickhandler.cloud.model.tables.EmailRecipient;
import io.clickhandler.cloud.model.tables.EmailRecipientJnl;
import io.clickhandler.cloud.model.tables.Evolution;
import io.clickhandler.cloud.model.tables.EvolutionChange;
import io.clickhandler.cloud.model.tables.File;
import io.clickhandler.cloud.model.tables.FileJnl;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface Tables {

	/**
	 * The table evolution_change
	 */
	public static final EvolutionChange EVOLUTION_CHANGE = io.clickhandler.cloud.model.tables.EvolutionChange.EVOLUTION_CHANGE;

	/**
	 * The table file
	 */
	public static final File FILE = io.clickhandler.cloud.model.tables.File.FILE;

	/**
	 * The table file_jnl
	 */
	public static final FileJnl FILE_JNL = io.clickhandler.cloud.model.tables.FileJnl.FILE_JNL;

	/**
	 * The table email
	 */
	public static final Email EMAIL = io.clickhandler.cloud.model.tables.Email.EMAIL;

	/**
	 * The table email_jnl
	 */
	public static final EmailJnl EMAIL_JNL = io.clickhandler.cloud.model.tables.EmailJnl.EMAIL_JNL;

	/**
	 * The table email_attachment
	 */
	public static final EmailAttachment EMAIL_ATTACHMENT = io.clickhandler.cloud.model.tables.EmailAttachment.EMAIL_ATTACHMENT;

	/**
	 * The table email_attachment_jnl
	 */
	public static final EmailAttachmentJnl EMAIL_ATTACHMENT_JNL = io.clickhandler.cloud.model.tables.EmailAttachmentJnl.EMAIL_ATTACHMENT_JNL;

	/**
	 * The table email_recipient
	 */
	public static final EmailRecipient EMAIL_RECIPIENT = io.clickhandler.cloud.model.tables.EmailRecipient.EMAIL_RECIPIENT;

	/**
	 * The table email_recipient_jnl
	 */
	public static final EmailRecipientJnl EMAIL_RECIPIENT_JNL = io.clickhandler.cloud.model.tables.EmailRecipientJnl.EMAIL_RECIPIENT_JNL;

	/**
	 * The table evolution
	 */
	public static final Evolution EVOLUTION = io.clickhandler.cloud.model.tables.Evolution.EVOLUTION;
}
