/**
 * This class is generated by jOOQ
 */
package data.schema;


import data.schema.tables.Email;
import data.schema.tables.EmailJnl;
import data.schema.tables.EmailRecipient;
import data.schema.tables.EmailRecipientJnl;
import data.schema.tables.Evolution;
import data.schema.tables.EvolutionChange;
import data.schema.tables.records.EmailJnlRecord;
import data.schema.tables.records.EmailRecipientJnlRecord;
import data.schema.tables.records.EmailRecipientRecord;
import data.schema.tables.records.EmailRecord;
import data.schema.tables.records.EvolutionChangeRecord;
import data.schema.tables.records.EvolutionRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<EmailRecord> PK_EMAIL = UniqueKeys0.PK_EMAIL;
	public static final UniqueKey<EmailJnlRecord> PK_EMAIL_JNL = UniqueKeys0.PK_EMAIL_JNL;
	public static final UniqueKey<EvolutionRecord> PK_EVOLUTION = UniqueKeys0.PK_EVOLUTION;
	public static final UniqueKey<EmailRecipientRecord> PK_EMAIL_RECIPIENT = UniqueKeys0.PK_EMAIL_RECIPIENT;
	public static final UniqueKey<EmailRecipientJnlRecord> PK_EMAIL_RECIPIENT_JNL = UniqueKeys0.PK_EMAIL_RECIPIENT_JNL;
	public static final UniqueKey<EvolutionChangeRecord> PK_EVOLUTION_CHANGE = UniqueKeys0.PK_EVOLUTION_CHANGE;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<EmailRecord> PK_EMAIL = createUniqueKey(Email.EMAIL, Email.EMAIL.ID);
		public static final UniqueKey<EmailJnlRecord> PK_EMAIL_JNL = createUniqueKey(EmailJnl.EMAIL_JNL, EmailJnl.EMAIL_JNL.ID, EmailJnl.EMAIL_JNL.VERSION);
		public static final UniqueKey<EvolutionRecord> PK_EVOLUTION = createUniqueKey(Evolution.EVOLUTION, Evolution.EVOLUTION.ID);
		public static final UniqueKey<EmailRecipientRecord> PK_EMAIL_RECIPIENT = createUniqueKey(EmailRecipient.EMAIL_RECIPIENT, EmailRecipient.EMAIL_RECIPIENT.ID);
		public static final UniqueKey<EmailRecipientJnlRecord> PK_EMAIL_RECIPIENT_JNL = createUniqueKey(EmailRecipientJnl.EMAIL_RECIPIENT_JNL, EmailRecipientJnl.EMAIL_RECIPIENT_JNL.ID, EmailRecipientJnl.EMAIL_RECIPIENT_JNL.VERSION);
		public static final UniqueKey<EvolutionChangeRecord> PK_EVOLUTION_CHANGE = createUniqueKey(EvolutionChange.EVOLUTION_CHANGE, EvolutionChange.EVOLUTION_CHANGE.ID);
	}
}
