/**
 * This class is generated by jOOQ
 */
package data.schema;


import data.schema.tables.Email;
import data.schema.tables.EmailJnl;
import data.schema.tables.EmailRecipient;
import data.schema.tables.EmailRecipientJnl;
import data.schema.tables.Evolution;
import data.schema.tables.EvolutionChange;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface Tables {

	/**
	 * The table email
	 */
	public static final Email EMAIL = data.schema.tables.Email.EMAIL;

	/**
	 * The table email_jnl
	 */
	public static final EmailJnl EMAIL_JNL = data.schema.tables.EmailJnl.EMAIL_JNL;

	/**
	 * The table evolution
	 */
	public static final Evolution EVOLUTION = data.schema.tables.Evolution.EVOLUTION;

	/**
	 * The table email_recipient
	 */
	public static final EmailRecipient EMAIL_RECIPIENT = data.schema.tables.EmailRecipient.EMAIL_RECIPIENT;

	/**
	 * The table email_recipient_jnl
	 */
	public static final EmailRecipientJnl EMAIL_RECIPIENT_JNL = data.schema.tables.EmailRecipientJnl.EMAIL_RECIPIENT_JNL;

	/**
	 * The table evolution_change
	 */
	public static final EvolutionChange EVOLUTION_CHANGE = data.schema.tables.EvolutionChange.EVOLUTION_CHANGE;
}
