/**
 * This class is generated by jOOQ
 */
package data.schema.tables.records;


import data.schema.tables.Email;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailRecord extends UpdatableRecordImpl<EmailRecord> implements Record9<String, Long, Timestamp, String, String, String, String, String, String> {

	private static final long serialVersionUID = -321614278;

	/**
	 * Setter for <code>email.id</code>.
	 */
	public EmailRecord setId(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>email.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>email.version</code>.
	 */
	public EmailRecord setVersion(Long value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>email.version</code>.
	 */
	public Long getVersion() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>email.changed</code>.
	 */
	public EmailRecord setChanged(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>email.changed</code>.
	 */
	public Timestamp getChanged() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>email.message_id</code>.
	 */
	public EmailRecord setMessageId(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>email.message_id</code>.
	 */
	public String getMessageId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>email.store_id</code>.
	 */
	public EmailRecord setStoreId(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>email.store_id</code>.
	 */
	public String getStoreId() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>email.html</code>.
	 */
	public EmailRecord setHtml(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>email.html</code>.
	 */
	public String getHtml() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>email.html_stripped</code>.
	 */
	public EmailRecord setHtmlStripped(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>email.html_stripped</code>.
	 */
	public String getHtmlStripped() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>email.text</code>.
	 */
	public EmailRecord setText(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>email.text</code>.
	 */
	public String getText() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>email.text_stripped</code>.
	 */
	public EmailRecord setTextStripped(String value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>email.text_stripped</code>.
	 */
	public String getTextStripped() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, String, String, String, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Long, Timestamp, String, String, String, String, String, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Email.EMAIL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return Email.EMAIL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Email.EMAIL.CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Email.EMAIL.MESSAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Email.EMAIL.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Email.EMAIL.HTML;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Email.EMAIL.HTML_STRIPPED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Email.EMAIL.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Email.EMAIL.TEXT_STRIPPED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getChanged();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMessageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getHtml();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getHtmlStripped();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getTextStripped();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value2(Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value3(Timestamp value) {
		setChanged(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value4(String value) {
		setMessageId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value5(String value) {
		setStoreId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value6(String value) {
		setHtml(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value7(String value) {
		setHtmlStripped(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value8(String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord value9(String value) {
		setTextStripped(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailRecord values(String value1, Long value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmailRecord
	 */
	public EmailRecord() {
		super(Email.EMAIL);
	}

	/**
	 * Create a detached, initialised EmailRecord
	 */
	public EmailRecord(String id, Long version, Timestamp changed, String messageId, String storeId, String html, String htmlStripped, String text, String textStripped) {
		super(Email.EMAIL);

		setValue(0, id);
		setValue(1, version);
		setValue(2, changed);
		setValue(3, messageId);
		setValue(4, storeId);
		setValue(5, html);
		setValue(6, htmlStripped);
		setValue(7, text);
		setValue(8, textStripped);
	}
}
