/**
 * This class is generated by jOOQ
 */
package data.schema.tables;


import data.schema.DefaultSchema;
import data.schema.Keys;
import data.schema.tables.records.EmailAttachmentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailAttachment extends TableImpl<EmailAttachmentRecord> {

	private static final long serialVersionUID = -74617502;

	/**
	 * The reference instance of <code>email_attachment</code>
	 */
	public static final EmailAttachment EMAIL_ATTACHMENT = new EmailAttachment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EmailAttachmentRecord> getRecordType() {
		return EmailAttachmentRecord.class;
	}

	/**
	 * The column <code>email_attachment.id</code>.
	 */
	public final TableField<EmailAttachmentRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>email_attachment.v</code>.
	 */
	public final TableField<EmailAttachmentRecord, Long> V = createField("v", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>email_attachment.c</code>.
	 */
	public final TableField<EmailAttachmentRecord, Timestamp> C = createField("c", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>email_attachment.name</code>.
	 */
	public final TableField<EmailAttachmentRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>email_attachment.description</code>.
	 */
	public final TableField<EmailAttachmentRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>email_attachment.mime_type</code>.
	 */
	public final TableField<EmailAttachmentRecord, String> MIME_TYPE = createField("mime_type", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>email_attachment.file_id</code>.
	 */
	public final TableField<EmailAttachmentRecord, String> FILE_ID = createField("file_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>email_attachment.email_id</code>.
	 */
	public final TableField<EmailAttachmentRecord, String> EMAIL_ID = createField("email_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>email_attachment</code> table reference
	 */
	public EmailAttachment() {
		this("email_attachment", null);
	}

	/**
	 * Create an aliased <code>email_attachment</code> table reference
	 */
	public EmailAttachment(String alias) {
		this(alias, EMAIL_ATTACHMENT);
	}

	private EmailAttachment(String alias, Table<EmailAttachmentRecord> aliased) {
		this(alias, aliased, null);
	}

	private EmailAttachment(String alias, Table<EmailAttachmentRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EmailAttachmentRecord> getPrimaryKey() {
		return Keys.PK_EMAIL_ATTACHMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EmailAttachmentRecord>> getKeys() {
		return Arrays.<UniqueKey<EmailAttachmentRecord>>asList(Keys.PK_EMAIL_ATTACHMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailAttachment as(String alias) {
		return new EmailAttachment(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EmailAttachment rename(String name) {
		return new EmailAttachment(name, null);
	}
}
