/**
 * This class is generated by jOOQ
 */
package data.schema.tables;


import data.schema.DefaultSchema;
import data.schema.Keys;
import data.schema.tables.records.SNSNotificationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SNSNotification extends TableImpl<SNSNotificationRecord> {

	private static final long serialVersionUID = 1608598733;

	/**
	 * The reference instance of <code>s_n_s_notification</code>
	 */
	public static final SNSNotification S_N_S_NOTIFICATION = new SNSNotification();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SNSNotificationRecord> getRecordType() {
		return SNSNotificationRecord.class;
	}

	/**
	 * The column <code>s_n_s_notification.id</code>.
	 */
	public final TableField<SNSNotificationRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>s_n_s_notification.version</code>.
	 */
	public final TableField<SNSNotificationRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>s_n_s_notification.changed</code>.
	 */
	public final TableField<SNSNotificationRecord, Timestamp> CHANGED = createField("changed", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>s_n_s_notification.type</code>.
	 */
	public final TableField<SNSNotificationRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>s_n_s_notification.message_id</code>.
	 */
	public final TableField<SNSNotificationRecord, String> MESSAGE_ID = createField("message_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>s_n_s_notification.topic_arn</code>.
	 */
	public final TableField<SNSNotificationRecord, String> TOPIC_ARN = createField("topic_arn", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>s_n_s_notification.subject</code>.
	 */
	public final TableField<SNSNotificationRecord, String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>s_n_s_notification.message</code>.
	 */
	public final TableField<SNSNotificationRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>s_n_s_notification.date</code>.
	 */
	public final TableField<SNSNotificationRecord, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>s_n_s_notification</code> table reference
	 */
	public SNSNotification() {
		this("s_n_s_notification", null);
	}

	/**
	 * Create an aliased <code>s_n_s_notification</code> table reference
	 */
	public SNSNotification(String alias) {
		this(alias, S_N_S_NOTIFICATION);
	}

	private SNSNotification(String alias, Table<SNSNotificationRecord> aliased) {
		this(alias, aliased, null);
	}

	private SNSNotification(String alias, Table<SNSNotificationRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SNSNotificationRecord> getPrimaryKey() {
		return Keys.PK_S_N_S_NOTIFICATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SNSNotificationRecord>> getKeys() {
		return Arrays.<UniqueKey<SNSNotificationRecord>>asList(Keys.PK_S_N_S_NOTIFICATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<SNSNotificationRecord, Long> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<SNSNotificationRecord, Timestamp> getRecordTimestamp() {
		return CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotification as(String alias) {
		return new SNSNotification(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SNSNotification rename(String name) {
		return new SNSNotification(name, null);
	}
}
