/**
 * This class is generated by jOOQ
 */
package data.schema.tables;


import data.schema.DefaultSchema;
import data.schema.Keys;
import data.schema.tables.records.SNSNotificationJnlRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SNSNotificationJnl extends TableImpl<SNSNotificationJnlRecord> {

	private static final long serialVersionUID = 1360269288;

	/**
	 * The reference instance of <code>s_n_s_notification_jnl</code>
	 */
	public static final SNSNotificationJnl S_N_S_NOTIFICATION_JNL = new SNSNotificationJnl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SNSNotificationJnlRecord> getRecordType() {
		return SNSNotificationJnlRecord.class;
	}

	/**
	 * The column <code>s_n_s_notification_jnl.id</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>s_n_s_notification_jnl.version</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>s_n_s_notification_jnl.changed</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, Timestamp> CHANGED = createField("changed", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>s_n_s_notification_jnl.type</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>s_n_s_notification_jnl.message_id</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, String> MESSAGE_ID = createField("message_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>s_n_s_notification_jnl.topic_arn</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, String> TOPIC_ARN = createField("topic_arn", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>s_n_s_notification_jnl.subject</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>s_n_s_notification_jnl.message</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>s_n_s_notification_jnl.date</code>.
	 */
	public final TableField<SNSNotificationJnlRecord, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>s_n_s_notification_jnl</code> table reference
	 */
	public SNSNotificationJnl() {
		this("s_n_s_notification_jnl", null);
	}

	/**
	 * Create an aliased <code>s_n_s_notification_jnl</code> table reference
	 */
	public SNSNotificationJnl(String alias) {
		this(alias, S_N_S_NOTIFICATION_JNL);
	}

	private SNSNotificationJnl(String alias, Table<SNSNotificationJnlRecord> aliased) {
		this(alias, aliased, null);
	}

	private SNSNotificationJnl(String alias, Table<SNSNotificationJnlRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SNSNotificationJnlRecord> getPrimaryKey() {
		return Keys.PK_S_N_S_NOTIFICATION_JNL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SNSNotificationJnlRecord>> getKeys() {
		return Arrays.<UniqueKey<SNSNotificationJnlRecord>>asList(Keys.PK_S_N_S_NOTIFICATION_JNL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<SNSNotificationJnlRecord, Long> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<SNSNotificationJnlRecord, Timestamp> getRecordTimestamp() {
		return CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SNSNotificationJnl as(String alias) {
		return new SNSNotificationJnl(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SNSNotificationJnl rename(String name) {
		return new SNSNotificationJnl(name, null);
	}
}
